### ISSUE TITLE
ValueError: When localhost is not accessible

### ISSUE THREAD

**Issue by jeffreyrobeson** [zhaoyun0071/OOTDiffusion-windows-GUI#2]
Running on local URL:  http://127.0.0.1:7865
*** 捕获到异常 <class 'ValueError'> When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.
Error in sys.excepthook:
Traceback (most recent call last):
  File "ottdiffusion_1_0_20230708.py", line 435, in handleException
AttributeError: 'traceback' object has no attribute 'print_tb'

Original exception was:
Traceback (most recent call last):
  File "ottdiffusion_1_0_20230708.py", line 378, in on_btn_rar_clicked
  File "gradio\blocks.py", line 2120, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.

**Comment by jeffreyrobeson** [comment]
如何加一行指令？set no_proxy=localhost, 127.0.0.1, ::1

**Comment by jeffreyrobeson** [comment]
ottdiffusion_1_0_20230708.py文件没找到？路径在哪？

**Comment by zhaoyun0071** [comment]
> ottdiffusion_1_0_20230708.py文件没找到？路径在哪？

按理说这个127.0.0.1电脑都可以吧，你是不是被占用了

**Comment by jeffreyrobeson** [comment]
我如何修改ottdiffusion_1_0_20230708.py这个文件的内容？

**Comment by zhaoyun0071** [comment]
> 我如何修改ottdiffusion_1_0_20230708.py这个文件的内容？

改不了

**Comment by zhaoyun0071** [comment]
> 我如何修改ottdiffusion_1_0_20230708.py这个文件的内容？

加qq群579385739 群文件有修复测试版

**Comment by Accurio** [comment]
如果使用代理服务器，需要设置 `HTTP_PROXY`、`HTTPS_PROXY` 和 `NO_PROXY` 环境变量。

```Python
import os
from urllib.request import getproxies

proxies = getproxies()
os.environ["http_proxy"]  = proxies["http"]
os.environ["https_proxy"] = proxies["https"]
os.environ["no_proxy"]    = "localhost, 127.0.0.1/8, ::1"
```
